#!/usr/bin/env node
/**
 * Podcast → Notes: Execute Module
 * 
 * Stores podcast notes in Obsidian vault.
 * 
 * Usage:
 *   node execute.js <analysis-file> [--destination <vault-path>]
 */

const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
const analysisFile = args[0];
const destArg = args.find(a => a.startsWith('--destination='));
const vaultPath = destArg ? destArg.split('=')[1] : process.env.OBSIDIAN_VAULT || '~/Obsidian/Melf2025';

if (!analysisFile || !fs.existsSync(analysisFile)) {
  console.error('❌ Error: Analysis file required and must exist');
  console.error('Usage: node execute.js <analysis-file> [--destination <vault-path>]');
  process.exit(1);
}

const analysis = JSON.parse(fs.readFileSync(analysisFile, 'utf8'));

// Template for podcast notes
const noteTemplate = (data) => {
  const tags = data.tags || data.analysis?.topics || ['podcast'];
  const tagString = tags.map(t => t.startsWith('#') ? t : `#${t}`).join(', ');

  return `---
tags: ${tagString}
created: ${new Date().toISOString().split('T')[0]}
source: ${data.url || 'Unknown'}
duration: ${data.analysis?.duration || 'Unknown'}
---

# 🎧 Podcast Notes

## Source
- **URL:** ${data.url || 'N/A'}
- **Duration:** ${data.analysis?.duration || 'Unknown'}
- **Date Processed:** ${new Date().toLocaleDateString()}

## Summary
${data.analysis?.summary || 'No summary available.'}

## 🎯 Key Insights

${data.analysis?.insights?.map(i => `- ${i}`).join('\n') || '- No insights extracted.'}

## 📝 Full Transcript

\`\`\`transcript
${data.transcript || 'No transcript available.'}
\`\`\`

## 🏷️ Topics
${tags.map(t => `- ${t.startsWith('#') ? t : `#${t}`}`).join('\n')}

---

*Generated by Podcast → Notes Skill*
`;
};

function getPodcastTitle(url) {
  // Extract title from URL or use timestamp
  if (!url) return `Podcast ${new Date().toISOString().slice(0, 10)}`;
  
  try {
    const urlObj = new URL(url);
    if (urlObj.hostname.includes('youtube.com') || urlObj.hostname.includes('youtu.be')) {
      return urlObj.searchParams.get('v') || 'YouTube Podcast';
    }
  } catch {}
  
  return url.split('/').pop() || 'Podcast';
}

function sanitizeFilename(title) {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 50);
}

async function main() {
  try {
    const resolvedVault = path.resolve(vaultPath.replace(/^~(?=\/|$)/, process.env.HOME || process.env.USERPROFILE || ''));
    const notesDir = path.join(resolvedVault, 'Podcast Notes');
    
    if (!fs.existsSync(notesDir)) {
      fs.mkdirSync(notesDir, { recursive: true });
      console.log(`📁 Created directory: ${notesDir}`);
    }
    
    const title = getPodcastTitle(analysis.url);
    const filename = `${sanitizeFilename(title)}.md`;
    const filepath = path.join(notesDir, filename);
    
    const noteContent = noteTemplate(analysis);
    fs.writeFileSync(filepath, noteContent, 'utf8');
    
    console.log(`✅ Notes saved to: ${filepath}`);
    console.log(`📄 File: ${filename}`);
    
    // Also update index
    const indexFile = path.join(notesDir, 'podcast-index.md');
    let indexContent = '# Podcast Notes Index\n\n';
    
    if (fs.existsSync(indexFile)) {
      indexContent = fs.readFileSync(indexFile, 'utf-8');
    }
    
    const entry = `- [[${filename.replace('.md', '')}]] - ${new Date().toLocaleDateString()} - ${analysis.analysis?.topics?.join(', ') || 'General'}`;
    
    // Prepend to index
    fs.writeFileSync(indexFile, `${entry}\n\n${indexContent}`);
    
    console.log(`📊 Updated index: ${indexFile}`);
    
  } catch (error) {
    console.error(`❌ Error saving notes: ${error.message}`);
    process.exit(1);
  }
}

main();
